### ISSUE TITLE
reload and add commands are not working

### ISSUE THREAD

**Issue by AggerTV** [SirLeezus/TabCompleteFilter#1]
The /tcf reload command doesn't work for me. I have to restart my entire server for any changes to take effect.
The /tcf add <group> <command> command also doesn't work for me.

Version 1.0.8
Server version: Tuinity 1.16.5

I did post this on spigot, but that was before I saw you had a github page for this :)

**Comment by SirLeezus** [comment]
Hmm, I'll take a look after work today.

**Comment by SirLeezus** [comment]
Yeah, tested it many times without any issue. Maybe try the latest version.
