### ISSUE TITLE
Some Commands are not Displayed

### ISSUE THREAD

**Issue by Pyario** [SirLeezus/TabCompleteFilter#2]
Some commands are not shown as TabComplete I don't know why.

Version from /version: 
This server is running Purpur version git-Purpur-1260 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) 
Plugin-Version: 1.1.0

Config: https://paste.gg/p/anonymous/1d91e8f458f2495eb69b5c3fd195b9f5

P.s: Commands from McMMO or other plugins do not work. Some are already going. Everything went well in 1.16.5. Possibly is it because of the 1.17.1? No idea.

Best Regards,

~Pyario

**Comment by SirLeezus** [comment]
I'll have to test it later but are you sure mcmmo has those commands registered with tab complete? Keep in mind this plugin doesn't add tab complete for commands, it only filters them.

**Comment by Pyario** [comment]
I think I know the mistake ...
If you try to take a "translate" command from another language, it does not work. Only the commands from plugin.yml work ... I wanted to use the commands as German names, but I have to use English unfortunately. Sorry, I made a mistake.

Best  Regards,

~Pyario
