### ISSUE TITLE
Issues with TabCompleteFilter v1.1.0

### ISSUE THREAD

**Issue by CrazyCloudCraft** [SirLeezus/TabCompleteFilter#3]
Hello SirLeezus,
i have a issue when i give someone the permission tcf.bypass it didn't bypass it. 
And even i delete the Plugin, i can't use tabbing. 

Server software: Paper (newest)
Minecraft version: 1.18.2

![2022-03-21_20 54 20](https://user-images.githubusercontent.com/95505222/159354486-a3ce7a98-4976-47d2-88ef-bc84e7a5a6cf.png)

**Comment by CrazyCloudCraft** [comment]
Okey, I see for this plugin is no support

**Comment by SirLeezus** [comment]
Try the latest version, it now supports 1.18 and 1.19. Sorry for the long delay.

**Comment by CrazyCloudCraft** [comment]
Thanks.
