### ISSUE TITLE
Group inheritance and new version

### ISSUE THREAD

**Issue by Bibithom** [SirLeezus/TabCompleteFilter#4]
Hi, i've tried to update to latest version, and group inheritance seems broken,
Is it still a feature, that when a player has multiple group, completion will stack up,
For example, player has group 1 which contain (/spawn) and he has a vip group which contain /fly, is it normal that this player has only /spawn in his completion list ?

This feature was my main reason to keep tabcompletefilter in my server, 'cause haven't seen it anywhere else. It will be a very great thing to keep it. 

Thank's in advance for your time, have a good day

**Comment by SirLeezus** [comment]
Yeah, that's how it should work, could you post your yml?

**Comment by SirLeezus** [comment]
Yeah, I just tested it, working with groups just fine. Just make sure the group has the permission tcf.{group} and the group has permissions for the filtered commands, otherwise it wont work.
