### ISSUE TITLE
Don't work on 1.19.3

### ISSUE THREAD

**Issue by Surax23** [SirLeezus/TabCompleteFilter#5]
Updated to Purpur #1876 and TCF has broken. There is no commands in tablist except Waterfall commands.

**Comment by SirLeezus** [comment]
Working fine on 1.19.3, if it isn't showing you a tablist you're likely not OP or don't have a group permission.

**Comment by Surax23** [comment]
Thanks for the reply. And Merry Christmas if it fits you.
> not OP
Yes, no op. Default players have only commands from Waterfall.
> don't have a group permission
I have "tcf.default" in default group and some other permissions in other groups. Trying with default group and no luck.

Config wasn't changed for a year and a some time ago I have upgraded to TCF 1.1.1. All was working then. But now I have upgraded to 1.19.3 and installed ViaBackwards plugin to Waterfall and maybe it's a cause TCF don't work.
If I delete TCF all commands in tablist become visible.

Interesting thing. In config you have string that points that `# Commands - List of registered commands that will show in tab complete [MUST NOT HAVE "/" IN CONFIG]` but there are slashes in the example and I added slashes (or two slashes because of WorldEdit) and all was fine.

**Comment by SirLeezus** [comment]
Hmm, could you send me your config.yml, the structure did change in the last update so if you updated without manually making that change it's likely the plugin isn't receiving the data correctly. You can also test this by generating a new config.yml and adding your desired commands for each group.

**Comment by Surax23** [comment]
Thank you!
With new config it works.
